spring:
    datasource:
    url: jdbc:h2:mem:courier_tracking_test
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
courier-log:
    duration: 1m
    availabilityDistanceInMeters: 100
